version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     image: wordpress:latest
     volumes:
       - wp_data:/var/www/html
     ports:
       - 80
     deploy:
       labels:
         - "traefik.frontend.rule=${TRAEFIK_FRONTEND_RULE}"
         - "traefik.port=80"
         - "traefik.docker.network=traefik-net"
     networks:
      - default
      - traefik-net
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

   backup:
     image: blacklabelops/volumerize:1.0
     volumes:
       - db_data:/source/db:ro
       - wp_data:/source/wp:ro
       - backup_data:/backup
     restart: always
     environment:
       TZ: ${VOLUMERIZE_TIMEZONE}
       VOLUMERIZE_SOURCE: /source
       VOLUMERIZE_TARGET: file:///backup
       VOLUMERIZE_JOBBER_TIME: ${VOLUMERIZE_JOBBER_TIME}

volumes:
    db_data:
    wp_data:
    backup_data:

networks:
    traefik-net:
      external: true
